sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tashima42/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tashima42/docker-react npm run test

deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU_API_KEY
  on:
    branch: main
