sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tashima42/client-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tashima42/client-dev npm run test

after_success:
  - docker build -t tashima42/multi-client ./client
  - docker build -t tashima42/multi-nginx ./nginx
  - docker build -t tashima42/multi-server ./server
  - docker build -t tashima42/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tashima42/multi-client
  - docker push tashima42/multi-nginx
  - docker push tashima42/multi-server
  - docker push tashima42/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'sa-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-sa-east-1-733095515052'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
