version: "3"
services:
  client:
    image: "tashima42/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "tashima42/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "tashima42/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "tashima42/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"

region: sa-east-1
app: multi-docker
bucket_name: elasticbeanstalk-sa-east-1-733095515052
bucket_path: docker-multi
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
